<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Resources\icon.ico</ApplicationIcon>
    <SupportedOSPlatformVersion>8.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\ef_unlock_plugin.dll" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\ef_unlock_plugin.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
  </ItemGroup>

</Project>
